name: Build ForgeOS
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: forgeos
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      security-events: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Buildah or Podman via Build Image Action
        uses: redhat-actions/buildah-build@v3
        id: build-image
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: latest
          containerfiles: |
            ./Containerfile

      - name: Log in to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: redhat-actions/podman-login@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Image to GHCR
        if: github.event_name != 'pull_request'
        uses: redhat-actions/push-to-registry@v3
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ${{ env.REGISTRY }}/${{ github.repository_owner }}

      - name: Install Cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@v3.8.1

      - name: Sign Container Image
        if: github.event_name != 'pull_request'
        run: |
          cosign sign --key env://COSIGN_PRIVATE_KEY ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.SIGNING_SECRET }}
          COSIGN_PASSWORD: "" 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Prune Old Image Versions
        if: github.event_name != 'pull_request'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Safely filters out Cosign signature (.sig) and attestation (.att) files before calculating the deletion line
          gh api /users/${{ github.repository_owner }}/packages/container/${{ env.IMAGE_NAME }}/versions --paginate \
            --template '{{range .}}{{if not (or (endWith .metadata.container.tags ".sig") (endWith .metadata.container.tags ".att"))}}{{.id}}{{"\n"}}{{end}}{{end}}' | tail -n +3 | xargs -I {} \
            gh api --method DELETE /users/${{ github.repository_owner }}/packages/container/${{ env.IMAGE_NAME }}/versions/{}
