name: Scheduled Registry Pruning
on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  clean:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Prune GHCR
        uses: step-security/ghcr-cleanup-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          keep-n-tagged: 5
          delete-untagged: true
